- hosts: all
  tasks:
  - name: Add repository
    yum_repository:
       name: "docker"
       description: "docker YUM REPO"
       baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable"
       gpgcheck: no
  - name: Install containerd.io
    yum:
       name: "https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.3.7-3.1.el7.x86_64.rpm"
       state: present
       disable_gpg_check: True
  - package:
       name: "docker-ce"
       state: present
  - service:
       name: "docker"
       state: started
  - name: Install Docker Module for Python
    pip:
       name: docker
  - name: pull docker image
    docker_image:
           name: "httpd"
           source: pull
  - name: Making a directory on managed node
    file:
          path: "/root/ansible_ws2"
          state: directory
  - name: Copying webpage to managed node directory
    copy:
          src: "my.html"
          dest: "/root/ansible_ws2"
  - name: Create a data container
    docker_container:
          name: "my_os_3"
          image: "httpd"
          volumes:
               - "/root/ansible_ws2:/usr/local/apache2/htdocs/"
          ports:
               - "901:80"
          state: started
          