- hosts: all
  vars_prompt: 
       name: dvd_dir
       private: no
       prompt: "enter dvd mount point"
  tasks:
  - file:
       state: directory
       path: "{{ dvd_dir }}"
  - mount:
       src: "/dev/cdrom"
       path: "{{ dvd_dir }}"
       state: mounted
       fstype: "iso9660"
  - yum_repository:
       baseurl: "{{ dvd_dir }}/AppStream"
       name: "mydvd1"
       description: "my yum dvd1 for package"
       gpgcheck: no
  - yum_repository:
       baseurl: "{{ dvd_dir }}/BaseOS"
       name: "mydvd2"
       description: "my yum dvd2 for package"
       gpgcheck: no
  - package:
       name: "httpd"
       state: present
  - file:
       state: directory
       path: "/var/www/lw"
  - copy:
       dest: "/etc/httpd/conf.d/lw.conf"
       src: "/root/lw.conf"
  - copy:
       dest: "/var/www/html/index.html"
       content: "this is my website \n"
  - service:
       name: "httpd"
       state: restarted
       enabled: yes
  - firewalld:
       port: "80/tcp"
       state: enabled
       permanent: yes
       immediate: yes

